cc_library(
    name = "joystick",
    srcs = [
        "button.cpp",
        "joystick.cpp",
    ],
    hdrs = [
        "button.h",
        "joystick.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//third_party/wpilibsuite:wpilib"],
)
