cc_library(
  name = 'teleop',
  srcs = ['teleop.cpp'],
  hdrs = ['teleop.h'],
  deps = [
    '//muan/teleop:joystick',
    '//generic_robot/queue_manager'
  ],
  visibility = ['//visibility:public']
)
