cc_library(
  name = 'wpilib_interface',
  srcs = [
    'wpilib_interface.cpp',
  ],
  hdrs = [
    'wpilib_interface.h',
  ],
  deps = [
    '//testbench/queue_manager',
    '//muan/wpilib:can_wrapper',
    '//muan/wpilib/gyro',
    '//third_party/wpilibsuite:wpilib',
  ],
  visibility = ['//visibility:public']
)
