set -e
bazel test --test_output=errors //muan/... -- -//muan/wpilib/... -//muan/teleop/...
bazel build //o2016/... --cpu=roborio
bazel test --test_output=errors //generic_robot/... -- -//generic_robot:frc1678 -//generic_robot/wpilib/... -//generic_robot/subsystem_runner/... -//generic_robot/wpilib_update/...
bazel test --test_output=errors //o2016/... -- -//o2016:frc1678 -//o2016/wpilib/... -//o2016/subsystem_runner/... -//o2016/teleop/...
bazel build //muan/... --cpu=roborio -- -//muan/vision/...
bazel build //generic_robot/... --cpu=roborio
./check-format.py --no-fail
