cc_library(
    name = "main",
    srcs = ["main.cpp"],
    hdrs = ["main.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//generic_robot/queue_manager",
        "//muan/teleop:joystick",
    ],
)
