cc_library(
    name = "main",
    srcs = ["main.cpp"],
    hdrs = ["main.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//o2017/queue_manager",
        "//muan/teleop:joystick",
        "//muan/wpilib:ds_sender",
    ],
)
