package(default_visibility = ["//visibility:public"])

cc_library(
    name = "score_subsystem",
    srcs = ["score_subsystem.cpp"],
    hdrs = ["score_subsystem.h"],
    restricted_to = ["//tools:roborio"],
    deps = [],
)