#ifndef MUAN_UTILS_PROTO_UTILS_H_
#define MUAN_UTILS_PROTO_UTILS_H_

#include <string>
#include "google/protobuf/message.h"
#include "third_party/aos/common/die.h"

namespace muan {

namespace util {

// Returns the contents of this message converted to a string that can be used
// as a line in a CSV file. This is ordered by field number, with empty fields
// represented by an empty string (This will appear as two commas next to each
// other).
std::string ProtoToCsv(const google::protobuf::Message& message);

// Returns a string that can be used as a header for a the lines of a CSV file
// generated by ProtoToCSV. This will have the names of all of the variables in
// the CSV, separated by commas and ordered by field number.
std::string ProtoToCsvHeader(const google::protobuf::Message& message);

}  // namespace util

}  // namespace muan

#endif  // MUAN_UTILS_PROTO_UTILS_H_
