package(default_visibility = ["//visibility:public"])

cc_library(
    name = "talon_wrapper",
    srcs = [
        "talon_wrapper.cpp",
    ],
    hdrs = ["talon_wrapper.h"],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//muan/units",
        "//third_party/phoenixsuite:phoenix",
    ],
)

cc_library(
    name = "victor_wrapper",
    srcs = [
        "victor_wrapper.cpp",
    ],
    hdrs = ["victor_wrapper.h"],
    restricted_to = ["//tools:roborio"],
    deps = [
        "//muan/units",
        "//third_party/phoenixsuite:phoenix",
    ]
)
