cc_library(
  name = 'wpilib_interface',
  srcs = [
    'wpilib_interface.cpp',
  ],
  hdrs = [
    'wpilib_interface.h',
  ],
  deps = [
    '//o2016/queue_manager',
    '//o2016/subsystems/drivetrain:queue_types',
    '//muan/wpilib:can_wrapper',
    '//third_party/wpilibsuite:wpilib',
  ]
)
