py_library(
  name = 'state_space_regression_lib',
  srcs = ['regression.py'],
  visibility = ['//visibility:public']
)

py_binary(
  name = 'state_space_regression',
  srcs = ['regression_main.py'],
  main = 'regression_main.py'
)
