cc_library(
    name = "queue_manager",
    srcs = ["queue_manager.cpp"],
    hdrs = ["queue_manager.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//muan/wpilib:wpilib_queues",
        "//muan/wpilib/gyro:gyro_queues",
        "//third_party/frc971/control_loops/drivetrain:drivetrain_lib",
    ],
)
