cc_library(
  name = 'teleop',
  srcs = ['teleop.cpp'],
  hdrs = ['teleop.h'],
  deps = [
    '//muan/teleop:joystick',
    '//testbench/queue_manager',
    '//testbench/subsystems/drivetrain:drivetrain_base',
    '//muan/actions:drivetrain_action',
  ],
  visibility = ['//visibility:public']
)
