cc_binary(
    name = "motor_calibration",
    srcs = ["motor_calibration.cpp",],
    deps =
        [
            "//c2018/teleop:main",
            "//muan/teleop:joystick",
            "//third_party/wpilibsuite:wpilib",
        ],
      visibility = ["//visibility:public"],
      restricted_to = ["//tools:roborio"]
)
