cc_binary(
  name = "motor_calibration",
  srcs = ["motor_calibration.cpp"],
  deps = ["//third_party/wpilibsuite:wpilib"],
  visibility = ["//visibility:public"],
  restricted_to = ["//tools:roborio"]
)
