cc_library(
  name = 'main',
  srcs = ['main.cpp'],
  hdrs = ['main.h'],
  deps = [
    '//muan/teleop:joystick',
    '//c2017/queue_manager',
    '//third_party/lemonscript',
    '//c2017/lemonscript:lemonscript',
    '//c2017/subsystems/drivetrain:drivetrain_base'
  ],
  visibility = ['//visibility:public']
)
