cc_library(
    name = "vision",
    srcs = ["vision.cpp"],
    hdrs = ["vision.h"],
    linkopts = [
        "-lopencv_imgproc",
        "-lopencv_core",
    ],
    #deps = ['//third_party/opencv:opencv'],
    visibility = ["//visibility:public"],
)
