cc_library(
    name = "drivetrain_base",
    srcs = ["drivetrain_base.cpp"],
    hdrs = ["drivetrain_base.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//muan/subsystems/drivetrain:drivetrain_config",
    ],
)
