cc_binary(
    name = "autostart",
    srcs = [
        "main.cpp"
    ],
    deps = [
        "//third_party/gflags:gflags"
    ],
    copts = [
        "-Wno-writable-strings"
    ],
    visibility = ["//visibility:public"]
)
