cc_library(
  name = 'subsystem_runner',
  srcs = ['subsystem_runner.cpp'],
  hdrs = ['subsystem_runner.h'],
  deps = [
    '//generic_robot/wpilib:wpilib_interface',
    '//third_party/aos/linux_code:init',
    '//third_party/aos/common/util:phased_loop',
    '//third_party/aos/common:time'],
  visibility = ['//visibility:public']
)

