cc_binary(
    name = "frc1678",
    srcs = ["main.cpp"],
    deps = [
        "//generic_robot/subsystem_runner",
        "//generic_robot/wpilib_update:main",
        "//third_party/wpilibsuite:wpilib",
    ],
)
