cc_binary(
    name = "frc1678",
    srcs = ["main.cpp"],
    deps = [
        "//testbench/subsystems:subsystem_runner",
        "//testbench/teleop",
    ],
    restricted_to = ["//tools:roborio"],
)
