cc_library(
    name = "teleop",
    srcs = ["teleop.cpp"],
    hdrs = ["teleop.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//muan/teleop:joystick",
        "//o2016/queue_manager",
    ],
)
