cc_binary(
    name = "frc1678",
    srcs = ["main.cpp"],
    deps = [
        "//c2017/subsystems:subsystem_runner",
        "//c2017/wpilib_update:main",
        "//third_party/wpilibsuite:wpilib",
    ],
)
